build.gradle, src/main/java/com/tobe/healthy/file/domain/entity/Files.java, src/main/java/com/tobe/healthy/member/domain/entity/BearerToken.java, src/main/java/com/tobe/healthy/member/domain/entity/Member.java, src/main/resources/application.yml, src/test/java/com/tobe/healthy/config/security/JwtTokenGeneratorTest.java
=> fix(설정파일 정보 환경변수 처리, id generator 전략 설정, h2 의존성, querydsl plugin 삭제)

src/main/java/com/tobe/healthy/common/CommonService.java, src/main/java/com/tobe/healthy/config/error/ErrorCode.java, src/main/java/com/tobe/healthy/config/security/JwtTokenProvider.java, src/main/java/com/tobe/healthy/file/domain/entity/WorkoutHistoryFile.java, src/main/java/com/tobe/healthy/member/repository/MemberRepository.java, src/main/java/com/tobe/healthy/trainer/respository/TrainerMemberMappingRepository.java, src/main/java/com/tobe/healthy/workout/application/CommentService.java, src/main/java/com/tobe/healthy/workout/application/WorkoutHistoryService.java, src/main/java/com/tobe/healthy/workout/domain/dto/WorkoutHistoryCommentDto.java, src/main/java/com/tobe/healthy/workout/domain/dto/WorkoutHistoryDto.java, src/main/java/com/tobe/healthy/workout/domain/dto/in/HistoryCommentAddCommand.java, src/main/java/com/tobe/healthy/workout/domain/entity/WorkoutHistory.java, src/main/java/com/tobe/healthy/workout/domain/entity/WorkoutHistoryComment.java, src/main/java/com/tobe/healthy/workout/domain/entity/WorkoutHistoryLike.java, src/main/java/com/tobe/healthy/workout/domain/entity/WorkoutHistoryLikePK.java, src/main/java/com/tobe/healthy/workout/presentation/CommentController.java, src/main/java/com/tobe/healthy/workout/presentation/WorkoutHistoryController.java, src/main/java/com/tobe/healthy/workout/repository/CommentRepository.java, src/main/java/com/tobe/healthy/workout/repository/WorkoutHistoryCommentRepository.java, src/main/java/com/tobe/healthy/workout/repository/WorkoutHistoryCommentRepositoryCustom.java, src/main/java/com/tobe/healthy/workout/repository/WorkoutHistoryCommentRepositoryCustomImpl.java, src/main/java/com/tobe/healthy/workout/repository/WorkoutHistoryLikeRepository.java, src/main/java/com/tobe/healthy/workout/repository/WorkoutHistoryLikeRepositoryCustom.java, src/main/java/com/tobe/healthy/workout/repository/WorkoutHistoryLikeRepositoryCustomImpl.java, src/main/java/com/tobe/healthy/workout/repository/WorkoutHistoryRepository.java, src/main/java/com/tobe/healthy/workout/repository/WorkoutHistoryRepositoryCustom.java, src/main/java/com/tobe/healthy/workout/repository/WorkoutHistoryRepositoryCustomImpl.java, src/main/resources/application.yml
운동기록/댓글 CRUD 추가
- 운동기록 댓글(답글) CRUD 추가
=> Tbh 80 workout

src/main/java/com/tobe/healthy/config/security/JwtTokenGenerator.java, src/main/java/com/tobe/healthy/member/application/MemberService.java, src/main/java/com/tobe/healthy/member/domain/dto/in/OAuthInfo.java, src/main/java/com/tobe/healthy/member/domain/entity/Member.java, src/main/java/com/tobe/healthy/member/domain/entity/Oauth.java, src/main/java/com/tobe/healthy/member/domain/entity/SocialType.java, src/main/java/com/tobe/healthy/member/domain/entity/Tokens.java, src/main/java/com/tobe/healthy/member/presentation/MemberController.java, src/main/java/com/tobe/healthy/member/repository/MemberRepository.java
=> Tbh 127  naver kakao api 

src/main/java/com/tobe/healthy/member/application/MemberService.java, src/main/java/com/tobe/healthy/member/domain/entity/OAuth.java, src/main/java/com/tobe/healthy/member/presentation/MemberController.java
=> fix: OAuth redirect URL 변경(https://api.to-be-healthy.site)

src/main/java/com/tobe/healthy/config/SwaggerConfig.java
=> fix: change swagger setting

src/main/resources/application.yml, src/test/resources/application.yml
=> fix application.yml

src/main/java/com/tobe/healthy/config/SwaggerConfig.java
=> fix: "change swagger setting"

src/main/java/com/tobe/healthy/gym/application/GymService.java, src/main/java/com/tobe/healthy/gym/domain/dto/TrainerCommandResult.java, src/main/java/com/tobe/healthy/gym/presentation/GymController.java, src/main/java/com/tobe/healthy/member/application/MemberService.java, src/main/java/com/tobe/healthy/member/repository/MemberRepository.java
=> feat: "gym 조회 api 추가"

src/main/java/com/tobe/healthy/gym/application/GymService.java, src/main/java/com/tobe/healthy/gym/presentation/GymController.java, src/main/java/com/tobe/healthy/member/application/MemberService.java, src/main/java/com/tobe/healthy/member/domain/dto/in/MemberFindIdCommand.java, src/main/java/com/tobe/healthy/member/presentation/MemberAuthController.java, src/main/java/com/tobe/healthy/member/repository/MemberRepository.java, src/main/java/com/tobe/healthy/schedule/presentation/ScheduleController.java, src/main/java/com/tobe/healthy/schedule/presentation/ScheduleWaitingController.java, src/main/java/com/tobe/healthy/trainer/domain/entity/TrainerMemberMapping.java, src/main/java/com/tobe/healthy/trainer/presentation/TrainerController.java, src/main/java/com/tobe/healthy/trainer/respository/TrainerMemberMappingRepository.java, src/main/java/com/tobe/healthy/workout/presentation/CommentController.java, src/main/java/com/tobe/healthy/workout/presentation/WorkoutHistoryController.java
=> Tbh 155  gym list

README.md
=> develop -> master merge

README.md
=> fix: "jenkins CI/CD 구현"

src/main/java/com/tobe/healthy/trainer/presentation/TrainerController.java
=> Style: 트레이너의 학생 상세조회, 트레이너가 내 학생으로 등록시 uri에 trainerId 제거

src/main/java/com/tobe/healthy/member/application/MemberService.java, src/main/java/com/tobe/healthy/member/domain/dto/in/MemoCommand.java, src/main/java/com/tobe/healthy/member/presentation/MemberController.java, src/main/java/com/tobe/healthy/member/repository/MemberRepositoryCustom.java, src/main/java/com/tobe/healthy/member/repository/MemberRepositoryImpl.java, src/main/java/com/tobe/healthy/trainer/application/TrainerService.java, src/main/java/com/tobe/healthy/trainer/domain/entity/TrainerMemberMapping.java, src/main/java/com/tobe/healthy/trainer/presentation/TrainerController.java, src/main/java/com/tobe/healthy/trainer/respository/TrainerMemberMappingRepository.java
- 트레이너가 가입된 회원 조회시 헬스장 조건 추가
- 트레이너가 학생 메모 수정 기능 구현
- 트레이너가 내 학생 삭제 기능 구현
=> 트레이너의 학생 메모, 학생 삭제 기능 추가

src/main/java/com/tobe/healthy/config/error/ErrorCode.java, src/main/java/com/tobe/healthy/member/presentation/MemberController.java, src/main/java/com/tobe/healthy/workout/application/CommentService.java, src/main/java/com/tobe/healthy/workout/application/WorkoutHistoryService.java, src/main/java/com/tobe/healthy/workout/domain/dto/WorkoutHistoryCommentDto.java, src/main/java/com/tobe/healthy/workout/presentation/CommentController.java, src/main/java/com/tobe/healthy/workout/presentation/WorkoutHistoryController.java, src/main/java/com/tobe/healthy/workout/repository/WorkoutHistoryCommentRepositoryCustomImpl.java
=> 운동기록 API 정리

src/main/java/com/tobe/healthy/course/application/CourseService.java, src/main/java/com/tobe/healthy/course/domain/dto/out/CourseGetResult.java, src/main/java/com/tobe/healthy/member/presentation/MemberController.java, src/main/java/com/tobe/healthy/point/application/PointService.java, src/main/java/com/tobe/healthy/point/domain/dto/PointDto.java, src/main/java/com/tobe/healthy/point/domain/dto/RankDto.java, src/main/java/com/tobe/healthy/point/domain/dto/out/PointGetResult.java, src/main/java/com/tobe/healthy/point/repository/PointRepository.java, src/main/java/com/tobe/healthy/point/repository/PointRepositoryCustom.java, src/main/java/com/tobe/healthy/point/repository/PointRepositoryCustomImpl.java, src/main/java/com/tobe/healthy/workout/application/WorkoutHistoryService.java, src/main/java/com/tobe/healthy/workout/repository/WorkoutHistoryRepositoryCustom.java, src/main/java/com/tobe/healthy/workout/repository/WorkoutHistoryRepositoryCustomImpl.java
=> 수강권 및 포인트 수정사항 반영

src/main/java/com/tobe/healthy/course/application/CourseService.java, src/main/java/com/tobe/healthy/diet/application/DietService.java, src/main/java/com/tobe/healthy/diet/domain/dto/DietDto.java, src/main/java/com/tobe/healthy/diet/domain/dto/in/DietAddCommand.java, src/main/java/com/tobe/healthy/diet/domain/entity/Diet.java, src/main/java/com/tobe/healthy/diet/presentation/DietController.java, src/main/java/com/tobe/healthy/diet/repository/DietRepositoryCustom.java, src/main/java/com/tobe/healthy/diet/repository/DietRepositoryCustomImpl.java, src/main/java/com/tobe/healthy/file/domain/dto/DietFileDto.java, src/main/java/com/tobe/healthy/member/presentation/MemberController.java, src/main/java/com/tobe/healthy/workout/application/CommentService.java, src/main/java/com/tobe/healthy/workout/application/ExerciseService.java, src/main/java/com/tobe/healthy/workout/domain/dto/WorkoutHistoryDto.java, src/main/java/com/tobe/healthy/workout/domain/entity/WorkoutHistory.java, src/main/java/com/tobe/healthy/workout/repository/WorkoutHistoryCommentRepository.java, src/main/java/com/tobe/healthy/workout/repository/WorkoutHistoryRepositoryCustomImpl.java
수강권 조회 수정, 운동/식단 목록 조회시 댓글수 같이 조회
=> 수강권 조회 수정, 운동/식단 목록 조회시 댓글수 같이 조회

src/main/resources/application.yml
=> fix: "redis 설정 변경"

src/main/kotlin/com/tobe/healthy/lessonHistory/application/LessonHistoryService.kt, src/main/kotlin/com/tobe/healthy/lessonHistory/domain/entity/LessonHistoryComment.kt, src/main/kotlin/com/tobe/healthy/lessonHistory/presentation/LessonHistoryController.kt, src/main/kotlin/com/tobe/healthy/lessonHistory/repository/LessonHistoryRepositoryCustom.kt
=> 수업 일지 댓글 삭제 기능 수정

src/main/java/com/tobe/healthy/common/aop/CourseAspect.java, src/main/java/com/tobe/healthy/common/aop/PointAspect.java, src/main/java/com/tobe/healthy/course/application/CourseService.java, src/main/java/com/tobe/healthy/course/domain/dto/CourseDto.java, src/main/java/com/tobe/healthy/home/application/HomeService.java, src/main/java/com/tobe/healthy/schedule/application/ScheduleWaitingService.java, src/main/java/com/tobe/healthy/schedule/application/StudentScheduleService.java, src/main/java/com/tobe/healthy/schedule/domain/entity/Schedule.java, src/main/java/com/tobe/healthy/schedule/repository/CommonScheduleRepository.java, src/main/java/com/tobe/healthy/schedule/repository/CommonScheduleRepositoryCustom.java, src/main/java/com/tobe/healthy/schedule/repository/CommonScheduleRepositoryCustomImpl.java, src/main/java/com/tobe/healthy/trainer/application/TrainerService.java, src/main/resources/logback-spring.xml
수강권 수정사항 반영
- 수강권 증가/차감 AOP 메소드 경로 수정
- 수강권 조회시 수업진행 횟수 추가 (총 횟수, 잔여횟수, 수업진행 횟수)
- 현재 사용중인 수강권 조회 메소드 분리
- logback-spring.xml 추가
=> 수강권 수정사항 반영

build.gradle.kts, src/main/java/com/tobe/healthy/common/Utils.java, src/main/java/com/tobe/healthy/common/event/CustomEventListener.java, src/main/java/com/tobe/healthy/config/security/SecurityConfig.java, src/main/java/com/tobe/healthy/member/application/MemberAuthCommandService.java, src/main/java/com/tobe/healthy/member/application/MemberAuthService.java, src/main/java/com/tobe/healthy/schedule/application/CommonScheduleService.java, src/main/java/com/tobe/healthy/trainer/application/TrainerService.java, src/main/java/com/tobe/healthy/workout/application/WorkoutCommentService.java, src/main/kotlin/com/tobe/healthy/common/NotificationSenderInfo.kt, src/main/kotlin/com/tobe/healthy/lessonhistory/application/LessonHistoryCommandService.kt, src/main/kotlin/com/tobe/healthy/notification/application/NotificationService.kt, src/main/kotlin/com/tobe/healthy/push/application/PushCommandService.kt, src/main/kotlin/com/tobe/healthy/schedule/application/TrainerScheduleCommandService.kt
=> fix: "도메인 변경으로 인한 코드 수정"
